name: Code Linter CI

on:
  push:
    branches:
      - "**" # matches every branch
    paths-ignore:
      - 'infrastructure/'
      
jobs:
  lint:
    name: checkout
    runs-on: ubuntu-20.04

    steps:
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: Set up python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Running isort check
        run: isort --check-only  .

      - name: Running flake8 check
        run: flake8 .