name: Terraform Linter CI

on:
  push:
    branches:
      - '**' # matches every branch
    paths:
      - 'infrastructure/'

jobs:
  lint:
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: terraform fmt
      uses: dflook/terraform-fmt-check@v1
      with:
        path: infrastructure/

    - name: terraform validate
      uses: dflook/terraform-validate@v1
      with:
        path: infrastructure/